services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: market-consumer-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
